<?php
	$work_arr = array(
		'Air-conditioning and refrigeration mechanic',
		'Architect',
		'Auto Car Repair',
		'Automotive electrician',
		'Cabler (data and telecommunications)',
		'Car mechanic',
		'Carpenter',
		'Construction',
		'Dog handler or trainor',
		'Dressmaker or tailor',
		'Electrical engineer',
		'Electrician (general)',
		'Electronics engineer',
		'Engineer (general)',
		'Farmer (general)',
		'Fashion designer',
		'Furniture designer and maker',
		'Gardener (general)',
		'Graphic designer',
		'Hairdresser',
		'Illustrator',
		'Industrial engineer',
		'Interior designer',
		'Jewelry designer',
		'Landscape gardener',
		'Maintenance',
		'Make-up artist',
		'Massage therapist',
		'Mechanical engineer',
		'Mobile developer',
		'Motor mechanic',
		'Motor mechanic (general)',
		'Motorcycle mechanic',
		'Moving service',
		'Multimedia designer',
		'Painter',
		'Photo editor',
		'Photographer ',
		'Plumber',
		'Programmer (general)',
		'Registered nurse (aged care)',
		'Registered nurse (child and family health)',
		'Registered nurse (community health)',
		'Registered nurse (critical care and emergency)',
		'Registered nurse (developmental disability)',
		'Registered nurse (disability and rehabilitation)',
		'Registered nurse (general)',
		'Registered nurse (mental health)',
		'Roof tiler',
		'Small engine mechanic',
		'Software tester',
		'System developer',
		'Systems analyst',
		'Teacher (general)',
		'Technician',
		'Toolmaker',
		'Tutor (general)',
		'Translator',
		'Vehicle body builder',
		'Vehicle painter',
		'Vehicle trimmer',
		'Video editor',
		'Wall and floor tiler',
		'Web designer',
		'Website developer',
		'Welder',
		'Writer'
	)
?>